print("нужно ввести два число")
x = int(input())
y = int(input())
print("Пожалуйста, выберите операцию (+, -, *, /)")
z = str(input())
if z == "+" : print(x + y)
if z == "-" : print(x - y)
if z == "*" : print(x * y)
if z == "/" : print(x / y)
